version: '2'
services:
  comparendos-app:
    image: comparendos
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://comparendos-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=comparendos
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://comparendos-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://comparendos-elasticsearch:9200
    ports:
      - 8080:8080
  comparendos-mongodb:
    extends:
      file: mongodb.yml
      service: comparendos-mongodb
  comparendos-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: comparendos-elasticsearch
